//
// Created by Administrator on 2019/3/27.
//

#ifndef POSTGRESQL_GLOBAL_DEFINE_H
#define POSTGRESQL_GLOBAL_DEFINE_H

#define PG_HOST 10.69.35.174
#define PG_PASSWORD 123456
#define PG_DATABASE TPCD
#define PG_TIMEOUT 10
#define PG_USER ilmare

#define STOCK_PER_WAREHOUSE 1568
#define DISTRICT_PER_WAREHOUSE 356
#define CUSTOMER_PER_DISTRICT 5489
#define ORDER_PER_DISTRICT 7854

#endif //POSTGRESQL_GLOBAL_DEFINE_H
