//
// Created by Administrator on 2019/3/27.
//

#ifndef POSTGRESQL_GLOBAL_DEFINE_H
#define POSTGRESQL_GLOBAL_DEFINE_H

#define MAX_ITEMS 100000
#define DISTRICT_PER_WAREHOUSE 10
#define CUSTOMER_PER_DISTRICT 3000
#define ORDER_PER_DISTRICT 3000

#endif //POSTGRESQL_GLOBAL_DEFINE_H
