//
// Created by Administrator on 2019/3/27.
//

#ifndef POSTGRESQL_GLOBAL_DEFINE_H
#define POSTGRESQL_GLOBAL_DEFINE_H

#define STOCK_PER_WAREHOUSE 156
#define DISTRICT_PER_WAREHOUSE 356
#define CUSTOMER_PER_DISTRICT 548
#define ORDER_PER_DISTRICT 3000

#endif //POSTGRESQL_GLOBAL_DEFINE_H
